---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 130.193.41.123
    jenkins-agent-01:
      ansible_host: 84.252.138.100
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: user
    ansible_ssh_private_key_file: /home/user/ssh_keys/id_rsa
